services:
  grpc-srv:
    build:
      context: .
      dockerfile: ./grpc-srv/Dockerfile
    ports:
      - "${EXPOSE_PORT:-50051}:${SERVER_PORT:-50051}"
      - "${HTTP_PORT:-8086}:${HTTP_PORT:-8086}"
    volumes:
      - ./:/workspace
    working_dir: /workspace/grpc-srv
    restart: always
    env_file:
      - ./grpc-srv/.env
    environment:
      SERVER_PORT: ${SERVER_PORT:-50051}

  grpc-client:
    build:
      context: .
      dockerfile: ./grpc-client/Dockerfile
    volumes:
      - ./:/workspace
    working_dir: /workspace/grpc-client
    restart: always
    environment:
      CERT_FILE: /workspace/cerificates/cert.pem
      TLS_SERVER_NAME: grpc-srv
    depends_on:
      - grpc-srv
